networks:
  web:
    external: true
  stack:
    external: false

volumes:
  database:
  redis:

services:
  database:
    image: mysql:8.0
    networks:
      - stack
    working_dir: /var/www/html
    volumes:
      - database:/var/lib/mysql:cached
      - ./docker/database/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    restart: always
    environment:
      - MYSQL_DATABASE=a11y
      - MYSQL_USER=a11y
      - MYSQL_PASSWORD=a11y
      - MYSQL_ROOT_PASSWORD=a11y
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=''

  application:
    build:
      context: .
      dockerfile: docker/application/application.Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    stop_grace_period: 1s
    extra_hosts:
      - "a11y.localhost:127.0.0.1"
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    networks:
      web:
        aliases:
          - a11y.localhost
      stack:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.a11y.rule=Host(`a11y.localhost`)"
      - "traefik.http.routers.a11y.entrypoints=web"
      - "traefik.http.services.a11y.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    restart: always

  tooling:
    build:
      context: .
      dockerfile: docker/tooling/tooling.Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    networks:
      - stack
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    restart: always
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"

  redis:
    image: redis:7.2-alpine
    networks:
      - stack
    restart: always
    volumes:
      - redis:/data
    command: >
      --requirepass a11y

  schedule:
    build:
      context: .
      dockerfile: docker/tooling/tooling.Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    init: true
    networks:
      - stack
    env_file:
      - .env
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    command: ["su", "vvuser", "-c", "php artisan schedule:work"]

  worker:
    build:
      context: .
      dockerfile: docker/tooling/tooling.Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    init: true
    networks:
      - stack
    env_file:
      - .env
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    command: ["su", "vvuser", "-c", "php artisan queue:listen --tries=3"]
