networks:
  web:
    external: true
  stack:
    external: false

volumes:
  storage:
  content:
  users:
  assets:
  redis:
  database:

services:
  application:
    build:
      context: .
      dockerfile: docker/application/application.Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    networks:
      - web
      - stack
    env_file:
      - .env
    volumes:
      - storage:/var/www/html/storage
      - content:/var/www/html/content
      - users:/var/www/html/users
      - assets:/var/www/html/public/assets
    working_dir: /var/www/html
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.a11yessentials.headers.stsseconds=31536000"
      - "traefik.http.routers.a11yessentials.middlewares=a11yessentials"
      - "traefik.http.routers.a11yessentials.rule=Host(`a11y-essentials.com`) || Host(`www.a11y-essentials.com`)"
      - "traefik.http.routers.a11yessentials.entrypoints=https,http"
      - "traefik.http.services.a11yessentials.loadbalancer.server.port=80"
      - "traefik.http.routers.a11yessentials.tls.certresolver=tls"
      - "traefik.docker.network=web"
    entrypoint: ["bash", "/var/www/html/docker/application/entrypoint.sh"]
    command: ["bash", "/var/www/html/docker/application/startup.sh"]

  redis:
    image: redis:7.2-alpine
    networks:
      - stack
    restart: always
    volumes:
      - redis:/data
    command: >
      --requirepass a11yessentials

  database:
    image: mysql:8.0
    networks:
      - stack
    working_dir: /var/www/html
    volumes:
      - database:/var/lib/mysql:cached
      - ./docker/database/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    restart: always
    environment:
      - MYSQL_DATABASE=a11yessentials
      - MYSQL_USER=a11yessentials
      - MYSQL_PASSWORD=a11yessentials
      - MYSQL_ROOT_PASSWORD=a11yessentials
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=''

  schedule:
    build:
      context: .
      dockerfile: docker/application/application.Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    init: true
    networks:
      - stack
    env_file:
      - .env
    volumes:
      - storage:/var/www/html/storage
      - content:/var/www/html/content
      - users:/var/www/html/users
      - assets:/var/www/html/public/assets
    working_dir: /var/www/html
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    command: ["su", "dorien", "-c", "php artisan schedule:work"]

  worker:
    build:
      context: .
      dockerfile: docker/application/application.Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    networks:
      - stack
    env_file:
      - .env
    volumes:
      - storage:/var/www/html/storage
      - content:/var/www/html/content
      - users:/var/www/html/users
      - assets:/var/www/html/public/assets
    working_dir: /var/www/html
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    command: ["su", "dorien", "-c", "php artisan queue:work --tries=3"]

